# Usa un'immagine base di Python 3
FROM python:3.11-slim

# Aggiorna il sistema e installa le dipendenze
RUN apt-get update && apt-get install -y \
    libgpiod-dev \
    python3-libgpiod

RUN ls -ltr /dev

# Imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia il file requirements.txt nella directory di lavoro
COPY requirements.txt .

# Installa le dipendenze presenti nel file requirements.txt
RUN pip3 install --break-system-packages --no-cache-dir -r requirements.txt

# Copia lo script Python nella directory di lavoro
COPY script-gpio.py .

# Comando di default per eseguire lo script Python
CMD ["python", "./script-gpio.py"]